title: Teaching Software Carpentry
email: info@software-carpentry.org
description: >
  Software Carpentry is a volunteer organization
  that teaches researchers how to get more done with computers
  in less time and with less pain.
baseurl: ""
twitter_username: swcarpentry
github_username: swcarpentry
github_projectname: training-course

collections:
  submissions:
    output: true

# Build settings
safe: true # because Github Pages
lsi: false # because Github Pages

markdown: kramdown
paginate: 10
paginate_path: blog/page:num/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "submissions"
    values:
      layout: "submission"

